[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200

; Required libraries
lib_deps =
    U8g2@^2.35.19

; Optional: enable all warnings
build_flags =
    -Wall
    -Wextra
